[package]
name = "askama"
version = "0.3.4"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
readme = "../README.md"

[badges]
travis-ci = { repository = "djc/askama" }

[dependencies]
askama_derive = { path = "../askama_derive", version = "0.3.4" }
error-chain = "0.10"
rocket = { version = "0.3", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
iron = { version = "0.5", optional = true }

[features]
serde-json = ["serde", "serde_json"]
default = []
with-iron = ["iron", "askama_derive/iron"]
with-rocket = ["rocket", "askama_derive/rocket"]

[package.metadata.docs.rs]
features = [ "serde-json" ]
