[package]
name = "askama"
version = "0.8.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2018"

[badges]
appveyor = { repository = "djc/askama" }
travis-ci = { repository = "djc/askama" }
maintenance = { status = "actively-developed" }

[features]
default = []
serde-json = ["askama_shared/serde_json"]
serde-yaml = ["askama_shared/serde_yaml"]
with-iron = ["iron", "askama_derive/iron"]
with-rocket = ["rocket", "askama_derive/rocket"]
with-actix-web = ["actix-web", "askama_derive/actix-web", "mime_guess"]
with-gotham = ["gotham", "askama_derive/gotham", "hyper", "mime_guess"]

[dependencies]
askama_derive = { version = "0.8.0", path = "../askama_derive" }
askama_escape = { version = "0.1.0", path = "../askama_escape" }
askama_shared = { version = "0.7.2", path = "../askama_shared" }
iron = { version = ">= 0.5, < 0.7", optional = true }
rocket = { version = "0.4", optional = true }
actix-web = { version = "0.7", optional = true }
mime_guess = { version = "2.0.0-alpha", optional = true }
gotham = { version = "0.3", optional = true }
hyper = { version = "0.12", optional = true }

[package.metadata.docs.rs]
features = [ "serde-json" ]
