[package]
name = "askama"
version = "0.11.2"
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["config", "humansize", "num-traits", "urlencode"]
config = ["askama_derive/config", "askama_shared/config"]
humansize = ["askama_derive/humansize", "askama_shared/humansize"]
markdown = ["askama_derive/markdown", "askama_shared/markdown"]
urlencode = ["askama_derive/urlencode", "askama_shared/percent-encoding"]
serde-json = ["askama_derive/serde-json", "askama_shared/json"]
serde-yaml = ["askama_derive/serde-yaml", "askama_shared/yaml"]
num-traits = ["askama_derive/num-traits", "askama_shared/num-traits"]
with-actix-web = ["askama_derive/with-actix-web", "askama_shared/actix-web"]
with-axum = ["askama_derive/with-axum", "askama_shared/axum"]
with-gotham = ["askama_derive/with-gotham", "askama_shared/gotham"]
with-mendes = ["askama_derive/with-mendes", "askama_shared/mendes"]
with-rocket = ["askama_derive/with-rocket", "askama_shared/rocket"]
with-tide = ["askama_derive/with-tide", "askama_shared/tide"]
with-warp = ["askama_derive/with-warp", "askama_shared/warp"]


# deprecated
mime = []
mime_guess = []

[dependencies]
askama_derive = { version = "0.12.0", path = "../askama_derive" }
askama_escape = { version = "0.10.3", path = "../askama_escape" }
askama_shared = { version = "0.13.0", path = "../askama_shared", default-features = false }

[package.metadata.docs.rs]
features = ["config", "humansize", "num-traits", "serde-json", "serde-yaml"]
