language: rust
rust:
  - 1.30.0 # minimum Rust version supported by Askama.
  - stable
  - beta
cache: cargo
matrix:
  include:
    - rust: nightly-2018-08-24
      script:
        - cd testing && cargo test --no-default-features --features with-rocket

before_script:
- rustup component add rustfmt-preview

script:
- cargo test --all
- if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    cargo fmt -- --check;
  fi
