language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

before_script:
- if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    rustup component add rustfmt;
  fi

script:
- cargo test --all
- cd askama_shared && cargo test --features full && cd ..
- if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    cd testing && cargo test --features full && cargo fmt -- --check;
  fi
- if [[ "${TRAVIS_RUST_VERSION}" == nightly ]]; then
    cd testing && cargo test --features with-rocket;
  fi
