[workspace]
members = [
    "askama",
    "askama_actix",
    "askama_gotham",
    "askama_derive",
    "askama_escape",
    "askama_iron",
    "askama_rocket",
    "askama_shared",
    "askama_tide",
    "askama_warp",
    "askama_routerify",
    "testing",
]

default-members = [
    "askama",
    "askama_derive",
    "askama_escape",
    "askama_shared",
    "testing",
]
