[package]
name = "askama_actix"
version = "0.11.1"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Actix-Web integration for Askama templates"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.6", default-features = false }
askama = { version = "0.10.6", path = "../askama", default-features = false, features = ["with-actix-web", "mime", "mime_guess"] }
bytes = { version = "1" }
futures-util = { version = "0.3" }

[dev-dependencies]
actix-rt = { version = "1", default-features = false }
