name: CI

on:
  push:
    branches: ['main']
  pull_request:
  schedule:
    - cron: "32 4 * * 5"

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        exclude:
          - os: macos-latest
            rust: beta
          - os: windows-latest
            rust: beta

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test

  Actix-Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
      - run: cargo test --package askama_actix --all-targets
      - run: cargo clippy --package askama_actix --all-targets -- -D warnings

  Axum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_axum --all-targets
      - run: cargo clippy --package askama_axum --all-targets -- -D warnings

  Gotham:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_gotham --all-targets
      - run: cargo clippy --package askama_gotham --all-targets -- -D warnings

  Rocket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_rocket --all-targets
      - run: cargo clippy --package askama_rocket --all-targets -- -D warnings

  Warp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_warp --all-targets
      - run: cargo clippy --package askama_warp --all-targets -- -D warnings

  Tide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_tide --all-targets
      - run: cargo clippy --package askama_tide --all-targets -- -D warnings

  Mendes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - run: cargo test --package askama_mendes --all-targets
      - run: cargo clippy --package askama_mendes --all-targets -- -D warnings

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
